[[constraint]]
  branch = "master"
  name = "github.com/google/tcpproxy"

[[constraint]]
  name = "github.com/rs/zerolog"
  version = "1.8.0"

[[constraint]]
  branch = "master"
  name = "golang.org/x/net"

[prune]
  go-tests = true
  unused-packages = true
